import { useCallback, useRef, useState } from 'react';
import { Image, Platform, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { AppModal, Button, FormField, Header, Screen } from '@/components/ui';
import { useApiQuery } from '@/hooks/useApiQuery';
import { colors } from '@/theme/colors';
import { createEmpresa, deleteEmpresa, listEmpresas, updateEmpresa, type Empresa } from '@/services/empresas.service';

export default function Empresas() {
  const inputRef = useRef<HTMLInputElement | null>(null); const [editing, setEditing] = useState<Empresa | null | undefined>(undefined); const [nome, setNome] = useState(''); const [file, setFile] = useState<File>(); const [errorMessage, setError] = useState(''); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState<Empresa | null>(null);
  const query = useCallback(() => listEmpresas(), []); const { data, loading, error, refetch } = useApiQuery(query, { fallbackData: [] }); const empresas = data ?? [];
  function open(item?: Empresa) { setEditing(item ?? null); setNome(item?.nome ?? ''); setFile(undefined); setError(''); }
  async function save() { if (nome.trim().length < 2 || (!editing && !file)) return setError('Informe o nome e selecione uma imagem.'); setSaving(true); try { const payload = { nome: nome.trim(), imagem: file, ativo: editing?.ativo ?? true, publicado: editing?.publicado ?? true, ordem: editing?.ordem ?? 0 }; editing ? await updateEmpresa(editing.id, payload) : await createEmpresa(payload); setEditing(undefined); refetch(); } catch (e) { setError((e as { message?: string }).message ?? 'Não foi possível salvar.'); } finally { setSaving(false); } }
  async function remove() { if (!deleting) return; try { await deleteEmpresa(deleting.id); setDeleting(null); refetch(); } catch (e) { setError((e as { message?: string }).message ?? 'Não foi possível excluir.'); } }
  return <Screen variant="admin"><Header title="Empresas" right={<TouchableOpacity onPress={() => open()} style={styles.plus}><MaterialCommunityIcons name="plus" color="#fff" size={24}/></TouchableOpacity>}/>
    {loading && <Text style={styles.state}>Carregando empresas...</Text>}{error && <Text style={styles.error}>{error}</Text>}
    <View style={styles.grid}>{empresas.map((item) => <View key={item.id} style={styles.card}><Image source={{ uri: item.imagemUrl }} resizeMode="contain" style={styles.logo}/><Text style={styles.name}>{item.nome}</Text><Text style={styles.status}>{item.publicado && item.ativo ? 'PUBLICADA' : 'OCULTA'}</Text><View style={styles.actions}><Button title="Editar" tone="green" onPress={() => open(item)}/><Button title="Excluir" tone="red" onPress={() => setDeleting(item)}/></View></View>)}</View>
    {!loading && !error && !empresas.length && <View style={styles.empty}><Text style={styles.name}>Nenhuma empresa cadastrada</Text><Text style={styles.state}>Cadastre patrocinadores e apoiadores para exibi-los na landing page.</Text></View>}
    {Platform.OS === 'web' && <input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" style={{display:'none'}} onChange={(e) => setFile(e.target.files?.[0])}/>} 
    <AppModal visible={editing !== undefined} onClose={() => setEditing(undefined)} title={editing ? 'Editar empresa' : 'Nova empresa'} footer={<View style={styles.actions}><Button title="Cancelar" tone="dark" onPress={() => setEditing(undefined)}/><Button title={saving ? 'Salvando...' : 'Salvar'} tone="green" onPress={saving ? undefined : save}/></View>}><FormField label="Nome" value={nome} onChangeText={setNome}/><TouchableOpacity style={styles.picker} onPress={() => inputRef.current?.click()}><MaterialCommunityIcons name="image-plus" color={colors.yellow} size={24}/><Text style={styles.state}>{file?.name ?? (editing ? 'Substituir logo/banner' : 'Selecionar logo/banner')}</Text></TouchableOpacity>{errorMessage && <Text style={styles.error}>{errorMessage}</Text>}</AppModal>
    <AppModal visible={!!deleting} onClose={() => setDeleting(null)} title="Excluir empresa" footer={<View style={styles.actions}><Button title="Cancelar" tone="dark" onPress={() => setDeleting(null)}/><Button title="Excluir" tone="red" onPress={remove}/></View>}><Text style={styles.state}>Confirma a exclusão de {deleting?.nome}? A imagem também será removida do Cloudinary.</Text></AppModal>
  </Screen>;
}
const styles=StyleSheet.create({plus:{backgroundColor:colors.red,width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},grid:{flexDirection:'row',flexWrap:'wrap',gap:14},card:{width:260,borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,padding:14},logo:{height:110,width:'100%',backgroundColor:'#fff',borderRadius:10},name:{color:colors.text,fontSize:17,fontWeight:'900',marginTop:10},status:{color:colors.green,fontSize:11,fontWeight:'900',marginVertical:8},actions:{flexDirection:'row',gap:10},state:{color:colors.muted,fontWeight:'700'},error:{color:colors.red,fontWeight:'800',marginVertical:8},empty:{padding:30,alignItems:'center'},picker:{marginTop:16,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:16,alignItems:'center',gap:8}});
